"""add unique constraint for daily wellness

Revision ID: 0df08cba0d91
Revises: ae7c8fe7562d
Create Date: 2026-03-02 15:41:11.746420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df08cba0d91'
down_revision: Union[str, Sequence[str], None] = 'ae7c8fe7562d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_employee_date', 'wellness_records', ['employee_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_employee_date', 'wellness_records', type_='unique')
    # ### end Alembic commands ###
