"""add unique constraint for daily wellness

Revision ID: 521b9e3dedc7
Revises: 0df08cba0d91
Create Date: 2026-03-02 15:44:29.718570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521b9e3dedc7'
down_revision: Union[str, Sequence[str], None] = '0df08cba0d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
